Repository GDSC-DGU/2024-SolutionChallenge-earlips-frontend, pull requests merged in 2024-05, with the labels that each got.

#58 ✨Feat: Vowles/단어와 함께 구현
  assets/icons/learning.svg
  assets/icons/mypage.svg
  assets/images/phoneme/vowels_1.jpg
  assets/images/phoneme/vowels_1.svg
  assets/images/phoneme/vowels_2.jpg
  assets/images/phoneme/vowels_2.svg
  assets/images/vowels_1.jpg
  assets/images/vowels_2.jpg
  lib/languages.dart
  lib/models/phoneme_model.dart
  lib/utilities/style/color_system.dart
  lib/views/auth/auth_dialog.dart
  lib/views/phoneme/phoneme_detail_screen.dart
  lib/views/phoneme/phoneme_screen.dart
  lib/views/phoneme/widget/phoneme_list_widget.dart
  lib/views/phoneme/widget/vowles_widget.dart
  lib/views/profile/widget/profile_header_widget.dart
  lib/views/root/custom_bottom_navigation_bar.dart
  lib/views/study/widget/study_main_body_widget.dart
  lib/views/word/widget/word_list_widget.dart
  lib/views/word/word_screen.dart
Labels: 🙋‍♂️ 희찬, size/XL

#59 ✨feat: 문단, 단어 스크린 수정 및 진동 기능 추가(문장스크린)
  android/app/src/main/AndroidManifest.xml
  assets/icons/vibrate.svg
  assets/images/output-onlinegiftools.gif
  assets/images/sound.png
  assets/images/sound_wave.gif
  lib/models/word_card_model.dart
  lib/views/script/create_script_screen.dart
  lib/views/script/learning_session_screen.dart
  lib/views/word/widget/sentence_alert_widget.dart
  lib/views/word/widget/word_result_dialog_widget.dart
  lib/views/word/widget/word_sentence_widget.dart
  lib/views/word/widget/word_vibration_widget.dart
  lib/views/word/word_screen.dart
  pubspec.yaml
Labels: 🙋‍♀️ 현정, size/XL

#60 ✨feat: 음소 교정 스크린 사진 추가
  assets/images/phoneme/vowels_1.jpg
  assets/images/phoneme/vowels_1.png
  assets/images/phoneme/vowels_1.svg
  assets/images/phoneme/vowels_2.jpg
  assets/images/phoneme/vowels_2.png
  assets/images/phoneme/vowels_2.svg
  lib/models/phoneme_model.dart
  lib/utilities/style/color_system.dart
  lib/views/phoneme/phoneme_detail_screen.dart
  pubspec.yaml
Labels: size/L

#61 ✨Feat: Gemini 추가
  lib/main.dart
  lib/viewModels/word/word_viewmodel.dart
  lib/views/phoneme/phoneme_detail_screen.dart
  lib/views/phoneme/widget/phoneme_list_widget.dart
  lib/views/phoneme/widget/vowles_widget.dart
  lib/views/script/learning_session_screen.dart
  lib/views/word/widget/phonetic_buttons_widget.dart
  lib/views/word/widget/word_sentence_widget.dart
  lib/views/word/widget/word_vibration_widget.dart
  lib/views/word/word_screen.dart
  pubspec.yaml
Labels: 🙋‍♂️ 희찬, size/XL, api 📬

#63 ✨feat: 오류 수정 및 동영상 GIF수정
  assets/images/sentance.gif
  assets/images/word.gif
  lib/bindings/root_binding.dart
  lib/models/phoneme_model.dart
  lib/views/phoneme/phoneme_detail_screen.dart
  lib/views/phoneme/vowel_datail_screen.dart
  lib/views/phoneme/widget/vowles_widget.dart
  lib/views/word/widget/phonetic_buttons_widget.dart
  lib/views/word/word_screen.dart
  pubspec.yaml
Labels: size/L
