Repository GDSC-DGU/2024-SolutionChallenge-earlips-frontend, pull requests merged in 2024-02, with the labels that each got.

#4 feat: 로그인 테스트, 칼라스킴 적용
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Base.lproj/Main.storyboard
  ios/Runner/GoogleService-Info_temp.plist
  lib/utilities/style/color_styles.dart
  lib/views/base/base_screen.dart
  lib/views/root/custom_bottom_navigation_bar.dart
  lib/views/root/root_screen.dart
Labels: 🙋‍♂️ 희찬, setting ⚙️, feature ✨

#7 Feature/profile
  lib/services/auth/auth_service.dart
  lib/utilities/style/color_styles.dart
  lib/utilities/validators/auth_validators.dart
  lib/viewModels/auth/email_login_viewmodel.dart
  lib/viewModels/auth/email_signup_viewmodel.dart
  lib/views/auth/email_login_screen.dart
  lib/views/auth/email_signup_screen.dart
  lib/views/auth/login_screen.dart
  lib/views/auth/logout_dialog.dart
  lib/views/profile/profile_divider_widget.dart
  lib/views/profile/profile_header_widget.dart
  lib/views/profile/profile_screen.dart
  lib/views/root/custom_bottom_navigation_bar.dart
  lib/views/root/root_screen.dart
Labels: 🙋‍♂️ 희찬, size/L, refactor 🔨, feature ✨, docs 📄

#10 ✨Feat : 로그인 화면 View 완성
  assets/icons/mailbox.svg
  assets/images/login_screen.png
  lib/views/auth/auth_card_widget.dart
  lib/views/auth/login_screen.dart
  lib/views/profile/profile_header_widget.dart
Labels: 🙋‍♂️ 희찬, size/L, feature ✨

#11 :sparkles: Feat: 로그인유지 기능 구현
  lib/services/auth/auth_service.dart
  lib/viewModels/auth/email_signup_viewmodel.dart
  lib/views/auth/logout_dialog.dart
  lib/views/root/root_screen.dart
Labels: 🙋‍♂️ 희찬, size/M, feature ✨

#15 ✨ Feat: 홈, 바텀네비게이션, 대본으로 학습하기 구현
  .idea/.gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/gradle.properties
  assets/icons/earlips_logo.png
  assets/icons/earlips_logo.svg
  assets/icons/home.svg
  assets/icons/learning.svg
  assets/icons/mypage.svg
  assets/icons/vuesax/linear/vuesax/bold/Vector.svg
  assets/icons/vuesax/linear/vuesax/bold/home.svg
  assets/images/home/Chart_new.png
  assets/images/home/circle.svg
  assets/images/home/fire.svg
  assets/images/home/three_circle.svg
  assets/images/home/vuesax/linear/vuesax/bold/home.svg
  ios/Podfile
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/utilities/app_routes.dart
  lib/viewModels/auth/email_login_viewmodel.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/viewModels/root/root_viewmodel.dart
  lib/views/home/create_script_screen.dart
  lib/views/home/home_screen.dart
  lib/views/home/learning_session_screen.dart
  lib/views/home/lib/bindings/root_binding.dart
  lib/views/home/lib/main.dart
  lib/views/home/lib/main_app.dart
  lib/views/home/lib/models/temp
  lib/views/home/lib/providers/temp
  lib/views/home/lib/repositories/temp
  lib/views/home/lib/services/auth/auth_service.dart
  lib/views/home/lib/utilities/style/color_styles.dart
  lib/views/home/lib/utilities/temp
  lib/views/home/lib/utilities/validators/auth_validators.dart
  lib/views/home/lib/viewModels/auth/email_login_viewmodel.dart
  lib/views/home/lib/viewModels/auth/email_signup_viewmodel.dart
  lib/views/home/lib/viewModels/home/home_viewmodel.dart
  lib/views/home/lib/viewModels/root/root_viewmodel.dart
  lib/views/home/lib/views/auth/auth_card_widget.dart
  lib/views/home/lib/views/auth/email_login_screen.dart
  lib/views/home/lib/views/auth/email_signup_screen.dart
  lib/views/home/lib/views/auth/login_screen.dart
  lib/views/home/lib/views/auth/logout_dialog.dart
  lib/views/home/lib/views/base/base_screen.dart
  lib/views/home/lib/views/base/base_widget.dart
  lib/views/home/lib/views/home/create_script_screen.dart
  lib/views/home/lib/views/home/home_screen.dart
  lib/views/home/lib/views/home/learning_session_screen.dart
  lib/views/home/lib/views/profile/profile_divider_widget.dart
  lib/views/home/lib/views/profile/profile_header_widget.dart
  lib/views/home/lib/views/profile/profile_screen.dart
  lib/views/home/lib/views/root/custom_bottom_navigation_bar.dart
  lib/views/home/lib/views/root/root_screen.dart
  lib/views/home/widget/app_resources.dart
  lib/views/home/widget/study_chart.dart
  lib/views/root/custom_bottom_navigation_bar.dart
  lib/views/root/root_screen.dart
  pubspec.yaml
Labels: 🙋‍♀️ 현정, size/L, feature ✨

#17 ✨ Feat : 실시간 발음테스트 페이지 구현, 안드로이드 녹음시간 증가
  lib/views/home/home_screen.dart
  lib/views/home/lib/bindings/root_binding.dart
  lib/views/home/lib/main.dart
  lib/views/home/lib/main_app.dart
  lib/views/home/lib/models/temp
  lib/views/home/lib/providers/temp
  lib/views/home/lib/repositories/temp
  lib/views/home/lib/services/auth/auth_service.dart
  lib/views/home/lib/utilities/style/color_styles.dart
  lib/views/home/lib/utilities/temp
  lib/views/home/lib/utilities/validators/auth_validators.dart
  lib/views/home/lib/viewModels/auth/email_login_viewmodel.dart
  lib/views/home/lib/viewModels/auth/email_signup_viewmodel.dart
  lib/views/home/lib/viewModels/home/home_viewmodel.dart
  lib/views/home/lib/viewModels/root/root_viewmodel.dart
  lib/views/home/lib/views/auth/auth_card_widget.dart
  lib/views/home/lib/views/auth/email_login_screen.dart
  lib/views/home/lib/views/auth/email_signup_screen.dart
  lib/views/home/lib/views/auth/login_screen.dart
  lib/views/home/lib/views/auth/logout_dialog.dart
  lib/views/home/lib/views/base/base_screen.dart
  lib/views/home/lib/views/base/base_widget.dart
  lib/views/home/lib/views/home/create_script_screen.dart
  lib/views/home/lib/views/home/home_screen.dart
  lib/views/home/lib/views/home/learning_session_screen.dart
  lib/views/home/lib/views/profile/profile_divider_widget.dart
  lib/views/home/lib/views/profile/profile_header_widget.dart
  lib/views/home/lib/views/profile/profile_screen.dart
  lib/views/home/lib/views/root/custom_bottom_navigation_bar.dart
  lib/views/home/lib/views/root/root_screen.dart
  lib/views/realtime/real_create_script_screen.dart
  lib/views/script/create_script_screen.dart
  lib/views/script/learning_session_screen.dart
Labels: 🙋‍♀️ 현정, size/XXL, feature ✨

#21 ✨ Feat : 추가된 대본페이지 생성, 분석 페이지 구현, 파일 전송 테스트
  assets/images/study/2.svg
  assets/images/study/3.svg
  assets/images/study/4.svg
  assets/images/study/one.svg
  devtools_options.yaml
  ios/Podfile.lock
  lib/bindings/root_binding.dart
  lib/main_app.dart
  lib/utilities/app_routes.dart
  lib/viewModels/script/analyze_viewmodel.dart
  lib/viewModels/script/create_script_viewmodel.dart
  lib/viewModels/study/study_viewmodel.dart
  lib/views/home/home_screen.dart
  lib/views/realtime/real_create_script_screen.dart
  lib/views/root/root_screen.dart
  lib/views/script/analyze_screen.dart
  lib/views/script/create_script_screen.dart
  lib/views/study/study_main.dart
  lib/views/study/widget/contribution.dart
  lib/views/test/sound_recorder.dart
  lib/views/test/test.dart
  pubspec.yaml
Labels: 🙋‍♀️ 현정, feature ✨

#22 ✨ FEAT : 로칼리제이션, 세이프아레아 설정
  assets/translations/en-US.json
  assets/translations/ko-KR.json
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/main.dart
  lib/main_app.dart
  lib/utilities/app_routes.dart
  lib/views/base/base_screen.dart
  lib/views/home/home_screen.dart
  lib/views/profile/profile_language_setting/profile_language_setting.dart
  lib/views/profile/profile_screen.dart
  lib/views/root/custom_bottom_navigation_bar.dart
  lib/views/root/root_screen.dart
  pubspec.yaml
Labels: 🙋‍♂️ 희찬, size/XL, feature ✨, design 🎨

#23 ✨ Feat: 홈 로그인 여부 판단
  lib/utilities/app_routes.dart
  lib/views/home/home_head_widget.dart
  lib/views/home/home_screen.dart
  lib/views/root/root_screen.dart
Labels: 🙋‍♂️ 희찬, size/L, feature ✨, design 🎨

#24 ✨ Feat: 메인 학습페이지, 일별 학습 스크린 구현 및 네비게이션 수정
  assets/images/study/1.png
  assets/images/study/2.png
  assets/images/study/2.svg
  assets/images/study/3.png
  assets/images/study/3.svg
  assets/images/study/4.png
  assets/images/study/4.svg
  assets/images/study/one.svg
  lib/utilities/app_routes.dart
  lib/utilities/temp
  lib/viewModels/study/date_study_screen_viewmodel.dart
  lib/views/root/custom_bottom_navigation_bar.dart
  lib/views/root/root_screen.dart
  lib/views/study/date_study_screen.dart
  lib/views/study/study_main.dart
  lib/views/study/widget/contribution.dart
Labels: 🙋‍♀️ 현정, size/L, feature ✨

#26 ✨Feat : Study main, haeder
  assets/icons/back.svg
  assets/icons/back_white.svg
  lib/utilities/style/color_styles.dart
  lib/views/base/default_back_appbar.dart
  lib/views/profile/profile_account/profile_account_screen.dart
  lib/views/profile/profile_header_widget.dart
  lib/views/profile/profile_language_setting/profile_language_setting.dart
  lib/views/script/create_script_screen.dart
  lib/views/study/date_study_screen.dart
  lib/views/study/study_main.dart
  lib/views/study/widget/contribution.dart
  lib/views/study/widget/study_card_widget.dart
  lib/views/study/widget/study_main_body_widget.dart
  lib/views/word/widget/blue_back_appbar.dart
  lib/views/word/word_screen.dart
Labels: 🙋‍♂️ 희찬, size/XL, PR status : done ✔️, feature ✨, design 🎨

#27 ✨Feat: 음소 교정 연동 및 구현
  ios/Podfile.lock
  lib/models/temp
  lib/models/user_word_model.dart
  lib/models/word_card_model.dart
  lib/models/word_data_model.dart
  lib/services/auth/auth_service.dart
  lib/viewModels/auth/email_signup_viewmodel.dart
  lib/viewModels/user/user_viewmodel.dart
  lib/viewModels/word/word_viewmodel.dart
  lib/views/word/widget/word_list_widget.dart
  lib/views/word/word_screen.dart
  pubspec.yaml
Labels: 🙋‍♂️ 희찬, size/XL, refactor 🔨, feature ✨, design 🎨

#28 ✨ Feat : 단어/음소/문장 데이터 불러오기
  assets/images/study/1.png
  assets/images/study/2.png
  assets/images/study/3.png
  assets/images/study/4.png
  ios/Runner/Info.plist
  lib/main.dart
  lib/models/word_card_model.dart
  lib/viewModels/word/word_viewmodel.dart
  lib/views/study/date_study_screen.dart
  lib/views/word/widget/word_list_widget.dart
  lib/views/word/word_screen.dart
Labels: 🙋‍♂️ 희찬, size/L, refactor 🔨, feature ✨

#29 ✨Feat: 영상 넘김 구현
  lib/viewModels/word/word_viewmodel.dart
  lib/views/word/widget/word_list_widget.dart
  lib/views/word/widget/word_youtube_widget.dart
  lib/views/word/word_screen.dart
Labels: 🙋‍♂️ 희찬, size/L, refactor 🔨, feature ✨

#30 Feat : 홈화면 그래프 뷰 구현 및 데이터베이스 연동
  lib/viewModels/root/root_viewmodel.dart
  lib/viewModels/user/user_viewmodel.dart
  lib/views/home/home_screen.dart
  lib/views/home/widget/study_chart.dart
  lib/views/root/root_screen.dart
Labels: size/XL

#32 ✨Feat: 문단 학습페이지 대본 페이지로, 대본 테스트 페이지 디자인 수정
  ios/Podfile.lock
  lib/views/home/widget/study_chart.dart
  lib/views/paragraph/analyze_screen.dart
  lib/views/paragraph/create_script_screen.dart
  lib/views/script/learning_session_screen.dart
  lib/views/study/widget/study_main_body_widget.dart
  lib/views/word/word_screen.dart
Labels: 🙋‍♀️ 현정, feature ✨, design 🎨

#34 ✨Feat: 데일리 기록
  ios/Podfile.lock
  lib/main_app.dart
  lib/utilities/app_routes.dart
  lib/viewModels/study/date_study_screen_viewmodel.dart
  lib/viewModels/word/word_viewmodel.dart
  lib/views/home/home_screen.dart
  lib/views/profile/profile_header_widget.dart
  lib/views/root/root_screen.dart
  lib/views/study/date_study_screen.dart
  lib/views/study/study_main.dart
  lib/views/study/widget/contribution.dart
  lib/views/study/widget/study_main_body_widget.dart
  lib/views/study/widget/study_row_card_widget.dart
  lib/views/word/widget/word_list_widget.dart
  lib/views/word/word_screen.dart
Labels: 🙋‍♂️ 희찬, feature ✨

#35 ✨Feat: 대본학습페이지 통신, 분석페이지 연동 및 수정
  android/app/build.gradle
  lib/viewModels/script/analyze_viewmodel.dart
  lib/viewModels/script/create_script_viewmodel.dart
  lib/views/script/analyze_screen.dart
Labels: size/L

#37 ✨Feat: 홈 문장 수정
  assets/translations/en.json
  assets/translations/ko.json
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/main.dart
  lib/utilities/base/supported_locale.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/viewModels/user/user_viewmodel.dart
  lib/views/home/home_head_widget.dart
  lib/views/word/widget/word_list_widget.dart
  lib/views/word/widget/word_sentence_widget.dart
  lib/views/word/word_screen.dart
Labels: 🙋‍♂️ 희찬, size/L, setting ⚙️

#38 [ FIX ] 대본으로 학습하기 API 연동 완료
  lib/viewModels/script/create_script_viewmodel.dart
Labels: 🙋‍♀️ 현정, size/M, refactor 🔨

#39 ✨Feat: 음소 서버 연동
  ios/Podfile.lock
  lib/models/record_word_model.dart
  lib/viewModels/record/record_viewmodel.dart
  lib/viewModels/script/create_script_viewmodel.dart
  lib/views/word/widget/word_list_widget.dart
  lib/views/word/widget/word_sentence_widget.dart
Labels: 🙋‍♂️ 희찬, size/L, refactor 🔨

#40 ✨Feat: 문단 교정 페이지 생성, DB연동
  lib/viewModels/Paragraph/learning_session_screen_viewmodel.dart
  lib/views/paragraph/analyze_screen.dart
  lib/views/paragraph/create_script_screen.dart
  lib/views/paragraph/learning_session_screen.dart
  lib/views/study/widget/study_main_body_widget.dart
  lib/views/word/word_screen.dart
Labels: 🙋‍♀️ 현정, feature ✨

#43 ✨Feat:녹음
  lib/viewModels/record/record_viewmodel.dart
  lib/views/word/widget/word_sentence_widget.dart
  lib/views/word/widget/word_youtube_widget.dart
  lib/views/word/word_screen.dart
Labels: size/L

#44 ✨Feat: 녹음 - 2
  lib/viewModels/record/record_viewmodel.dart
  lib/views/word/widget/word_sentence_widget.dart
Labels: size/L

#46 fix: 음소 인식 페이지 오류 수정
  lib/viewModels/record/record_viewmodel.dart
  lib/views/word/widget/word_sentence_widget.dart
Labels: size/S

#47 ✨Feat: 문장 API연동
  lib/views/home/home_screen.dart
  lib/views/study/date_study_screen.dart
  lib/views/word/widget/word_sentence_widget.dart
Labels: 🙋‍♂️ 희찬, size/XL, refactor 🔨, feature ✨

#48 Update README.md
  README.md
Labels: size/L

#49 ✨ Feat: language, chart
  lib/languages.dart
  lib/viewModels/record/record_viewmodel.dart
  lib/views/word/widget/fail_word_dialog_widget.dart
  lib/views/word/widget/highlight_mistake_text_widget.dart
  lib/views/word/widget/sentence_alert_widget.dart
  lib/views/word/widget/sentence_guide_widget.dart
  lib/views/word/widget/sucess_word_dialog_widget.dart
  lib/views/word/widget/word_result_dialog_widget.dart
  lib/views/word/widget/word_sentence_widget.dart
  lib/views/word/word_screen.dart
Labels: size/XXL

#50 ✨ Feat : 다국어 및 리펙토링 적용
  assets/images/home/Chart-1.png
  assets/images/home/Chart_new.png
  lib/languages.dart
  lib/main_app.dart
  lib/services/auth/auth_service.dart
  lib/utilities/style/color_styles.dart
  lib/utilities/validators/auth_validators.dart
  lib/viewModels/Paragraph/learning_session_screen_viewmodel.dart
  lib/viewModels/auth/email_login_viewmodel.dart
  lib/viewModels/auth/email_signup_viewmodel.dart
  lib/viewModels/record/record_viewmodel.dart
  lib/viewModels/root/root_viewmodel.dart
  lib/viewModels/script/analyze_viewmodel.dart
  lib/viewModels/script/create_script_viewmodel.dart
  lib/viewModels/script/learning_session_screen_viewmodel.dart
  lib/viewModels/user/user_viewmodel.dart
  lib/viewModels/word/word_viewmodel.dart
  lib/views/auth/auth_card_widget.dart
  lib/views/auth/auth_dialog.dart
  lib/views/auth/email_login_screen.dart
  lib/views/auth/email_signup_screen.dart
  lib/views/auth/login_screen.dart
  lib/views/base/default_back_appbar.dart
  lib/views/home/home_head_widget.dart
  lib/views/home/home_screen.dart
  lib/views/home/widget/app_resources.dart
  lib/views/home/widget/bottom_widget.dart
  lib/views/home/widget/mid_widget.dart
  lib/views/home/widget/study_chart.dart
  lib/views/home/widget/top_widget.dart
  lib/views/paragraph/analyze_screen.dart
  lib/views/paragraph/create_script_screen.dart
  lib/views/paragraph/learning_session_screen.dart
  lib/views/profile/profile_account/profile_account_screen.dart
  lib/views/profile/profile_header_widget.dart
  lib/views/profile/profile_language_setting/profile_language_setting.dart
  lib/views/profile/profile_screen.dart
  lib/views/profile/profile_setting_row_box_widget.dart
  lib/views/realtime/real_create_script_screen.dart
  lib/views/script/analyze_screen.dart
  lib/views/script/create_script_screen.dart
  lib/views/script/learning_session_screen.dart
  lib/views/script/user_script_screen.dart
  lib/views/study/date_study_screen.dart
  lib/views/study/study_main.dart
  lib/views/study/widget/contribution.dart
  lib/views/study/widget/study_card_widget.dart
  lib/views/study/widget/study_main_body_widget.dart
  lib/views/study/widget/study_row_card_widget.dart
  lib/views/test/sound_recorder.dart
  lib/views/test/test.dart
  lib/views/word/widget/blue_back_appbar.dart
  lib/views/word/widget/fail_word_dialog_widget.dart
  lib/views/word/widget/highlight_mistake_text_widget.dart
  lib/views/word/widget/sentence_alert_widget.dart
  lib/views/word/widget/sentence_guide_widget.dart
  lib/views/word/widget/sucess_word_dialog_widget.dart
  lib/views/word/widget/word_result_dialog_widget.dart
  lib/views/word/widget/word_youtube_widget.dart
  lib/views/word/word_screen.dart
Labels: 🙋‍♂️ 희찬, size/XXL, feature ✨

#51 ✨feat : 영어
  lib/languages.dart
  lib/views/home/home_head_widget.dart
  lib/views/study/widget/contribution.dart
  lib/views/word/word_screen.dart
Labels: size/S

#52 Update README.md
  README.md
Labels: size/M
